version: '3.3'
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.2.0
    ports:
      - "8082:8080"
    environment:
      PARAMS: '
        --spring.datasource.url=jdbc:mysql://192.168.36.23:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        --spring.datasource.username=root
        --spring.datasource.password=123456
        --xxl.job.accessToken=cmii'
    volumes:
      - /data/common/xxl-job/data:/data
